### ISSUE TITLE
How to Make Lualine Transparent?

### ISSUE THREAD

**Issue by itokun99** [amedoeyes/eyes.nvim#4]
The transparent feature was really great before 😊, I could adjust the opacity with the terminal I was using. I really appreciate that 🙏.

Now I’ve encountered a small issue 😅, it turns out that it doesn't make the lualine transparent.
I’m attaching a screenshot below 📸.

![Image](https://github.com/user-attachments/assets/2cc8208c-f87f-46c8-acad-c336773c71c2)

I'm using Lazyvim

**Comment by amedoeyes** [comment]
Done.

**Comment by itokun99** [comment]
Hi @amedoeyes, I updated the theme, but it’s still not transparent. Could I be missing some configuration?

![Image](https://github.com/user-attachments/assets/bcbfd703-3e4f-4520-b337-3b3737bef01b)

here is my configuration

![Image](https://github.com/user-attachments/assets/c09e79c9-1ac1-4e14-b894-7095598bb676)

**Comment by amedoeyes** [comment]
@itokun99 hmmm did you set the theme of lualine? like so:

```
require("lualine").setup({ options = { theme = "eyes" } })
```

**Comment by itokun99** [comment]
I don't think so. Just setup follow by guide lazyvim

![Image](https://github.com/user-attachments/assets/540dc810-a6f1-4af6-a8ac-cb735f66af95)

I trying to add setup but still not work

**Comment by amedoeyes** [comment]
You have to set lualine theme manually like this:
```lua
{
  "nvim-lualine/lualine.nvim",
  opts = {
    options = {
      theme = "eyes",
    }
  }
}
```

**Comment by itokun99** [comment]
Ah i see, i missing wrap with `options`, now i't working 😄 , Thank you
